name: "Determine tag name"
description: "Determine the tag name to use for a release"
outputs:
  name:
    description: "The name of the tag"
    value: ${{ steps.tag.outputs.name }}

runs:
  using: "composite"
  steps:
    - name: Determine tag name
      id: tag
      shell: bash
      run: |
        DATE_TAG="$(date -u +%Y-%m-%d)"
        BASE_TAG="${DATE_TAG}"

        # Find existing tags for this date (e.g., 2025-12-09, 2025-12-09-2, ...)
        EXISTING_TAGS="$(git tag --list "${BASE_TAG}*")"

        if [[ -z "${EXISTING_TAGS}" ]]; then
          NAME="${BASE_TAG}"
        else
          NEXT_SUFFIX=2
          while read -r tag; do
            SUFFIX="${tag#${BASE_TAG}}"
            if [[ "${SUFFIX}" =~ ^-([0-9]+)$ ]]; then
              N="${BASH_REMATCH[1]}"
              if (( N >= NEXT_SUFFIX )); then
                NEXT_SUFFIX=$((N + 1))
              fi
            fi
          done <<< "${EXISTING_TAGS}"
          NAME="${BASE_TAG}-${NEXT_SUFFIX}"
        fi

        echo "name=${NAME}" >> $GITHUB_OUTPUT
